name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        version: [3.8, 3.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.version}}
      - run: pip install build wheel
      - run: python plano build
        env:
          PYTHONPATH: subrepos/plano/src
      - run: pip install dist/ssorj_brbn-1.0.0-py3-none-any.whl
      - run: brbn-self-test
  # fedora:
  #   runs-on: ubuntu-latest
  #   container: fedora:latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: dnf -y install make pip python python-build python-wheel
  #     - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
  #     - run: brbn-self-test
